# name of our workflow
name: Django CI/CD Workflow

# triggers for our workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Python 3.6
          uses: actions/setup-python@v2
          with:
              python-version: 3.6
        - name: Install requirements
          run: pip install -r requirements.txt
        - name: Run Tests
          run: |
            python manage.py test
